### ISSUE TITLE
Consider MIT license

### ISSUE THREAD

**Issue by p-decoraid** [yovasx2/RspecCapybara101#10]
Code under AGPL license is generally unusable for people working with proprietary software. As this repository is meant to be a starting point for one's testing efforts, AGPL license means it cannot be used by most proprietary projects/developers.

Also, the license file in the repository is for GPL not AGPL (readme states AGPL).

**Comment by yovasx2** [comment]
Ok I'm new with licenses, could you please make the PR

**Comment by yovasx2** [comment]
https://github.com/yovasx2/RspecCapybara101/pull/11

**Comment by p-decoraid** [comment]
Thanks!
